import '../../model/categories.dart';

import '../../model/category.dart';
import '../../model/task.dart';
import 'category_manager.dart';

class CategoryManagerImpl implements CategoryManager {
  @override
  List<Category> initializeCategories() {
    const mindfulnessTasks = [
      Task("Meditate for 10 minutes"),
      Task("Practice deep breathing for 5 minutes"),
      Task("Write down 3 things you’re grateful for."),
      Task("Take a 20-minute walk without your phone."),
      Task("Spend 30 minutes reading a self-help book."),
      Task("Journal about your feelings and thoughts today."),
      Task("Complete a digital detox for an hour."),
      Task("Do a 15-minute yoga session."),
      Task("Listen to calming music while reflecting on your day."),
      Task("Perform a random act of kindness."),
      Task("Take a relaxing bath with essential oils."),
      Task("Unplug all electronics 1 hour before bed."),
      Task("Practice mindfulness eating with one meal."),
      Task("Set up a cozy reading nook and read for pleasure."),
      Task("Start a gratitude jar and add your first note."),
      Task("Do a body scan meditation before bed."),
      Task("Spend 10 minutes coloring or drawing."),
      Task("Watch a sunrise or sunset without distractions."),
      Task("Learn about a new relaxation technique and try it."),
      Task("Create a vision board for your personal goals."),
      Task("Declutter a small area in your home for peace of mind."),
      Task("Try a new herbal tea for relaxation."),
      Task("Write a letter to your future self."),
      Task("List 5 things you love about yourself."),
      Task("Spend time gardening or caring for houseplants."),
      Task("Practice positive affirmations in the mirror."),
      Task(
          "Identify and write down stress triggers, brainstorm coping mechanisms."),
      Task("Craft something by hand, like a card or small gift."),
      Task("Do a guided imagery exercise to relax."),
      Task("Plan a small, solo adventure to a place you’ve never been."),
    ];

    const physicalHealthTasks = [
      Task("Complete a 30-minute cardio workout."),
      Task("Drink 2 liters of water throughout the day."),
      Task("Try a new vegetable or fruit."),
      Task("Do 10,000 steps."),
      Task("Start your day with a healthy breakfast."),
      Task("Complete a strength training session."),
      Task("Track your food intake for the day."),
      Task("Attempt a new sport or physical activity."),
      Task("Go for a bike ride in a nearby park."),
      Task("Prepare all your meals from scratch today."),
      Task("Join a local sports team or club."),
      Task("Take a dance class."),
      Task("Skip processed sugar for the day."),
      Task("Do a 20-minute stretching routine."),
      Task("Try a meal without meat."),
      Task("Learn about macronutrients and plan a balanced meal."),
      Task("Attend a fitness class you’ve never tried before."),
      Task("Track your sleep and aim for 7-9 hours."),
      Task("Swap an unhealthy habit for a healthy one for the day."),
      Task("Complete a ‘couch to 5k’ run."),
      Task("Plan a week of healthy meals."),
      Task("Do a full-body workout with no equipment."),
      Task("Experiment with a new healthy recipe."),
      Task("Try intermittent fasting for a day."),
      Task("Use a standing desk for part of your workday."),
      Task("Participate in a local race or fitness challenge."),
      Task("Do a home workout with a family member or friend."),
      Task("Take a rest day and focus on hydration and nutrition."),
      Task("Learn a new exercise and incorporate it into your routine."),
      Task("Evaluate your fitness goals and progress, adjust as needed."),
    ];

    const personalDevelopmentTasks = [
      Task("Read a chapter of a non-fiction book."),
      Task("Listen to a podcast on a topic you know little about."),
      Task("Set up a monthly budget."),
      Task("Write down your short-term and long-term goals."),
      Task("Learn about a historical event you’re curious about."),
      Task("Watch a documentary on a subject outside your comfort zone."),
      Task("Practice public speaking or storytelling skills."),
      Task("Identify a habit you’d like to change and plan the first step."),
      Task("Take an online course on a skill you want to improve."),
      Task("Spend 30 minutes learning a new language."),
      Task("Reflect on your failures and the lessons learned."),
      Task("Reach out to a professional mentor or coach."),
      Task("Organize your workspace for better efficiency."),
      Task("Update your CV and LinkedIn profile."),
      Task("Write a personal mission statement."),
      Task("Practice a new time management technique."),
      Task("Identify and write down your core values."),
      Task("Network with someone in your field."),
      Task("Implement a new learning into your daily life."),
      Task("Create a personal website or blog."),
      Task("Attend a webinar or workshop."),
      Task("Review and adjust your personal development plan."),
      Task("Try a new productivity app."),
      Task("Set up a professional goal for the next 6 months."),
      Task("Give feedback to a colleague or friend."),
      Task(
          "Write a letter to yourself, highlighting your achievements this year."),
      Task("Plan a solo travel experience."),
      Task("Attend a networking event or meet-up."),
      Task("Start a side project or hobby that could turn into a business."),
      Task("Identify a fear and take one step towards overcoming it."),
    ];

    const creativityAndLearningTasks = [
      Task("Draw or paint something from your surroundings."),
      Task("Write a short story or poem."),
      Task("Learn to play a new song on an instrument."),
      Task("Take photos of your city from a new perspective."),
      Task("Cook a new recipe from a different cuisine."),
      Task("Start a DIY project at home."),
      Task("Create a mood board for a dream project."),
      Task("Experiment with a new art form or craft."),
      Task("Listen to music from a genre you don’t usually prefer."),
      Task("Enroll in a creative writing workshop."),
      Task("Design your dream home layout."),
      Task("Learn about a new culture through its art."),
      Task("Upcycle an old item into something new."),
      Task("Write a review of a book, film, or restaurant."),
      Task("Learn the basics of a new craft or technique."),
      Task("Participate in a local art or craft fair."),
      Task("Try your hand at pottery or ceramic making."),
      Task("Visit an art gallery or museum you’ve never been to."),
      Task("Create a piece of digital art."),
      Task("Experiment with making your own music."),
      Task("Design and send a custom greeting card."),
      Task("Try writing with your non-dominant hand."),
      Task("Create a playlist for someone you care about."),
      Task("Learn a magic trick."),
      Task("Sew or knit something simple."),
      Task("Participate in a creative challenge online."),
      Task("Build a simple piece of furniture or home decor."),
      Task("Doodle or sketch for 15 minutes."),
      Task("Experiment with a new hairstyle or makeup look."),
      Task("Repurpose a clothing item creatively."),
    ];

    const productivityAndOrganization = [
      Task("Declutter your digital files for 30 minutes."),
      Task("Unsubscribe from unnecessary email newsletters."),
      Task("Set up a weekly meal planning routine."),
      Task("Organize your workspace to enhance productivity."),
      Task("Create a to-do list for the next day each evening."),
      Task("Implement the 'two-minute rule' for small tasks."),
      Task("Set specific time blocks for checking emails."),
      Task("Plan your outfits for the week."),
      Task("Digitally detox for a set period of time."),
      Task("Use a planner or digital app to organize your tasks."),
      Task("Prioritize your tasks using the Eisenhower Box."),
      Task("Clean out your wardrobe and donate unused items."),
      Task("Set a goal for a clutter-free zone in your home."),
      Task("Try a new note-taking method."),
      Task("Audit your time spent on social media and set limits."),
      Task("Prepare a financial savings plan."),
      Task("Organize all important documents digitally."),
      Task("Set up automatic bill payments."),
      Task("Create a personal workflow for repetitive tasks."),
      Task("Identify and eliminate one time-wasting habit."),
      Task("Optimize your morning routine for a productive start."),
      Task("Review and adjust your goals for the year."),
      Task("Practice the Pomodoro Technique for a day."),
      Task("Develop a system for managing your emails."),
      Task("Schedule 'me time' for self-care activities."),
      Task("Create an inventory of your pantry and refrigerator."),
      Task("Plan a no-spend weekend."),
      Task("Rearrange your living space for a fresh perspective."),
      Task("Set up a donation box for items to give away."),
      Task("Implement a nightly routine for better sleep hygiene."),
    ];

    const socialAndEmotionalWellBeingTasks = [
      Task("Compliment three people today."),
      Task("Write a thank-you note to someone who has helped you."),
      Task("Schedule a catch-up with an old friend."),
      Task("Reflect on your emotional responses for the day."),
      Task("Practice active listening in all conversations."),
      Task("Volunteer for a local community service."),
      Task("Join a club or group related to your interests."),
      Task("Share a meal with someone without using phones."),
      Task("Identify and express your feelings through art or journaling."),
      Task("Call a family member to check in."),
      Task("Engage in a hobby that involves other people."),
      Task("Practice saying 'no' to something that doesn't serve you."),
      Task("Participate in a local meet-up or workshop."),
      Task("Donate to a cause you’re passionate about."),
      Task("Send an uplifting message to someone going through a tough time."),
      Task("Attend a support group or therapy session."),
      Task("Practice gratitude by listing friendships you’re thankful for."),
      Task("Make a new friend by reaching out to someone."),
      Task("Share your personal story or experience with others."),
      Task("Offer to help a friend or neighbor with a task."),
      Task("Host a game night or social gathering."),
      Task("Engage in team sports or group fitness activities."),
      Task("Navigate a difficult conversation with empathy."),
      Task("Plan a family or friends' day out."),
      Task("Meditate on love and kindness for those around you."),
      Task("Engage in a random act of kindness anonymously."),
      Task("Learn about a different culture through a social event."),
      Task("Teach someone a skill or knowledge you possess."),
      Task(
          "Participate in a cultural or religious celebration different from your own."),
      Task("Spend a day focusing on self-love and acceptance."),
    ];

    const categories = [
      Category(
        PersonalGrowCategories.mindfulnessAndWellBeing,
        mindfulnessTasks,
      ),
      Category(
        PersonalGrowCategories.physicalHealth,
        physicalHealthTasks,
      ),
      Category(
        PersonalGrowCategories.personalDevelopment,
        personalDevelopmentTasks,
      ),
      Category(
        PersonalGrowCategories.creativityAndLearning,
        creativityAndLearningTasks,
      ),
      Category(
        PersonalGrowCategories.productivityAndOrganization,
        productivityAndOrganization,
      ),
      Category(
        PersonalGrowCategories.socialAndEmotionalWellBeing,
        socialAndEmotionalWellBeingTasks,
      ),
    ];

    return categories;
  }
}
